[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "chemlibrary-chempy"
version = "2.3.1"
authors = [
  { name="Chem", email="codechem@proton.me" },
]
description = "Chems Python Library."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/chemlibrary/chempy"

[tool.setuptools.packages.find]
where = ["src"]
